version: '3'
services:
  ambassador_backend:
    build:
      context: .
      dockerfile: prod.dockerfile
    image: antoniopapa/ambassador:0.0.2
    command: "go run main.go"
    ports:
      - 8003:8000
    environment:
      DB_HOST:
      DB_PORT: 3306
      DB_DATABASE: ambassador
      DB_USERNAME: root
      DB_PASSWORD: root
      BOOTSTRAP_SERVERS:
      SECURITY_PROTOCOL: SASL_SSL
      SASL_USERNAME:
      SASL_PASSWORD:
      SASL_MECHANISM: PLAIN
      KAFKA_TOPIC: ambassador_topic
      USERS_MS: http://users-ms:8000
      REDIS_CONNECTION: "redis:6379"

  ambassador_queue:
    build:
      context: .
      dockerfile: prod.dockerfile
    image: antoniopapa/ambassador:0.0.1
    command: "go run src/commands/consumer.go"
    environment:
      DB_HOST:
      DB_PORT: 3306
      DB_DATABASE: ambassador
      DB_USERNAME: root
      DB_PASSWORD: root
      BOOTSTRAP_SERVERS:
      SECURITY_PROTOCOL: SASL_SSL
      SASL_USERNAME:
      SASL_PASSWORD:
      SASL_MECHANISM: PLAIN
      KAFKA_TOPIC: ambassador_topic
      USERS_MS: http://users-ms:8000
      REDIS_CONNECTION: "redis:6379"

  redis:
    image: redis:latest
    ports:
      - 6379:6379